// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa8UJK5wlqQ5oN3opFXnYr9tNA9CoUlZI',
    appId: '1:613487542993:web:48f675f2dd9130c82cfbf0',
    messagingSenderId: '613487542993',
    projectId: 'baghdad-company',
    authDomain: 'baghdad-company.firebaseapp.com',
    storageBucket: 'baghdad-company.appspot.com',
    measurementId: 'G-0WB4HPY99P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlQLtIQY21Qzs0GYIZwP87607SsfNNnY',
    appId: '1:613487542993:android:732aca625665858f2cfbf0',
    messagingSenderId: '613487542993',
    projectId: 'baghdad-company',
    storageBucket: 'baghdad-company.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfkQXxhbOpkiJyOQG5J-FdL0F11Ewxffo',
    appId: '1:613487542993:ios:3347289f0dbf03fb2cfbf0',
    messagingSenderId: '613487542993',
    projectId: 'baghdad-company',
    storageBucket: 'baghdad-company.appspot.com',
    iosBundleId: 'com.example.baghdadcompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfkQXxhbOpkiJyOQG5J-FdL0F11Ewxffo',
    appId: '1:613487542993:ios:3347289f0dbf03fb2cfbf0',
    messagingSenderId: '613487542993',
    projectId: 'baghdad-company',
    storageBucket: 'baghdad-company.appspot.com',
    iosBundleId: 'com.example.baghdadcompany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa8UJK5wlqQ5oN3opFXnYr9tNA9CoUlZI',
    appId: '1:613487542993:web:52ffb639d3f101a72cfbf0',
    messagingSenderId: '613487542993',
    projectId: 'baghdad-company',
    authDomain: 'baghdad-company.firebaseapp.com',
    storageBucket: 'baghdad-company.appspot.com',
    measurementId: 'G-L1G09RFKGZ',
  );
}
